# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               EDA Blogs
tagline:             'Examination Development & Analysis with Blogs'
description:         'Custom recovery for Zenfone 5, custom roms,latest firmware and mods,root android, zenfone 5 xda,asus zenfone 5 xda, All other Stuff and news'
url:                 "http://lite.edablogs.com"
baseurl:             ""
paginate: 4
paginate_path: "page:num/"

# About/contact
author:
  name:              Pawneshwer Gupta
  url:               http://edablogs.com
  twitter: https://twitter.com/pawneshwer
  email:             pawneshwergupta@gmail.com

authors: 
  pawneshwer: 
    name: "Pawneshwer Gupta"
    position: "Software Developer and Web Developer"
    avatar: "/assets/users/pawneshwer/photo.jpg"
    web: "http://edablogs.com"
    github: "edablogs"
    email: "pawneshwergupta@gmail"
    linkedin: "https://www.linkedin.com/in/pawneshwer"
    twitter: "https://twitter.com/pawneshwer"
    pinterest: "https://www.pinterest.com/xdablogs/"
    facebook: "https://www.facebook.com/pawneshwerr.gupta"
    google: "https://plus.google.com/116495809884069789298"
    about: |    
         "I am Software developer and web developer and also part time blogger."
  edablogs:
    name: "EDA Blogs"
    position: "Software Developer and Web Developer"
    avatar: "/assets/users/edablogs/photo.jpg"
    web: "http://edablogs.com"
    github: "edablogs"
    email: "edablogs247@gmail.com"
    pinterest: "https://www.pinterest.com/xdablogs/"
    linkedin: "https://www.linkedin.com/in/pawneshwer"
    facebook: "https://www.facebook.com/XDAblogsOfficial"
    google: "https://plus.google.com/+XDAblogss"
    twitter: "https://twitter.com/XDABlogs"
    about: |    
         "I am Software developer and web developer and also part time blogger."
logo: '/assets/logo.png'

  
facebook:
  app_id: 1378587825791443
  publisher: 100002825163498

# Custom vars
version:             1.0.0
permalink: /:categories/:title

rouge: true

popular_posts_count: 5

# Build settings
markdown: kramdown

include: ['.htaccess']

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
